# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iMarket' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iMarket
    pod 'SwiftLint'
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore' 
#    pod 'Firebase/Database'

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          if Gem::Version.new('8.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] 
          end
        end
      end
    end
end
